package com.ccooy.expandablerecyclerview.decoration

class Source{
    companion object {
        const val JSON_FROM_SERVICE_SUMMARY = """[
            {
                "time":"2020-04-24",
                "count":"33",
                "amount":"22",
                "discount_num":"2",
                "discount_amount":"90"
            },
            {
                "time":"2020-04-23",
                "count":"15",
                "amount":"10",
                "discount_num":"2",
                "discount_amount":"90"
            },
            {
                "time":"2020-04-22",
                "count":"1",
                "amount":"10",
                "discount_num":"2",
                "discount_amount":"90"
            },
            {
                "time":"2020-04-21",
                "count":"1",
                "amount":"10",
                "discount_num":"2",
                "discount_amount":"90"
            },
            {
                "time":"2020-04-20",
                "count":"1",
                "amount":"10",
                "discount_num":"2",
                "discount_amount":"90"
            },
            {
                "time":"2020-04-19",
                "count":"1",
                "amount":"10",
                "discount_num":"2",
                "discount_amount":"90"
            },
            {
                "time":"2020-04-18",
                "count":"1",
                "amount":"10",
                "discount_num":"2",
                "discount_amount":"90"
            },
            {
                "time":"2020-04-17",
                "count":"1",
                "amount":"10",
                "discount_num":"2",
                "discount_amount":"90"
            },
            {
                "time":"2020-04-16",
                "count":"1",
                "amount":"10",
                "discount_num":"2",
                "discount_amount":"90"
            },
            {
                "time":"2020-04-15",
                "count":"1",
                "amount":"10",
                "discount_num":"2",
                "discount_amount":"90"
            }
        ]"""

        const val JSON_FROM_SERVICE_TRADE = """[
            {
                "type":"支付宝",
                "money":"20.00"
            },
            {
                "type":"支付宝",
                "money":"19.00"
            },
            {
                "type":"微信",
                "money":"20.00"
            },
            {
                "type":"支付宝",
                "money":"18.00"
            },
            {
                "type":"支付宝",
                "money":"21.00"
            },
            {
                "type":"支付宝",
                "money":"21.00"
            },
            {
                "type":"支付宝",
                "money":"19.00"
            },
            {
                "type":"微信",
                "money":"20.00"
            },
            {
                "type":"支付宝",
                "money":"18.00"
            },
            {
                "type":"支付宝",
                "money":"21.00"
            }
        ]"""
    }
}